// CLI builder. Template drift for `sato-kit doctor`: when the working directory
// holds a repo generated by create-sato-agent (./sato.create.json), send that
// file and ./sato.lock.json to Sato Hub's drift endpoint and report the changes
// it names. Read-only: this never opens an issue, never edits a file, and never
// fills in a change the endpoint did not return. Anything short of a
// well-formed sato.template-drift/v1 answer within the timeout is reported as
// unavailable with the reason.
import { readFile } from "node:fs/promises";
import { join } from "node:path";

export const DRIFT_URL = "https://satohub.ai/api/create/drift";
export const DRIFT_SCHEMA = "sato.template-drift/v1";
export const DRIFT_KINDS = ["template_update", "custody_change", "upstream_break"] as const;
export type DriftKind = (typeof DRIFT_KINDS)[number];

export type DriftChange = { key: string; kind: DriftKind; title: string; body_markdown: string; evidence_urls: string[] };
export type DriftTemplate = {
  id: string;
  framework: string;
  pinned_version: string | null;
  pinned_digest: string | null;
  latest_version: string | null;
  latest_digest: string | null;
  latest_last_green: string | null;
};

export type DriftReport =
  | { state: "not_applicable"; reason: string }
  | { state: "unavailable"; url: string | null; reason: string }
  | { state: "checked"; url: string; template: DriftTemplate; changes: DriftChange[] };

type DriftFetch = (url: string, init: { method: string; signal: AbortSignal; headers: Record<string, string>; body: string }) => Promise<{ ok: boolean; status: number; json(): Promise<unknown> }>;

function isObj(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}
const strOrNull = (v: unknown): v is string | null => v === null || typeof v === "string";

async function readJson(path: string): Promise<{ missing: true } | { value: unknown } | { error: string }> {
  let text: string;
  try {
    text = await readFile(path, "utf8");
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return { missing: true };
    return { error: (e as Error).message };
  }
  try {
    return { value: JSON.parse(text) };
  } catch {
    return { error: "not valid JSON" };
  }
}

/** Validates the endpoint's answer. Returns null when it is not a well-formed drift document. */
export function parseDriftResponse(doc: unknown): { template: DriftTemplate; changes: DriftChange[] } | null {
  if (!isObj(doc) || doc.schema !== DRIFT_SCHEMA || !isObj(doc.template) || !Array.isArray(doc.changes)) return null;
  const t = doc.template;
  if (typeof t.id !== "string" || typeof t.framework !== "string") return null;
  for (const k of ["pinned_version", "pinned_digest", "latest_version", "latest_digest", "latest_last_green"] as const) {
    if (k in t && !strOrNull(t[k])) return null;
  }
  const template: DriftTemplate = {
    id: t.id,
    framework: t.framework,
    pinned_version: (t.pinned_version as string | null | undefined) ?? null,
    pinned_digest: (t.pinned_digest as string | null | undefined) ?? null,
    latest_version: (t.latest_version as string | null | undefined) ?? null,
    latest_digest: (t.latest_digest as string | null | undefined) ?? null,
    latest_last_green: (t.latest_last_green as string | null | undefined) ?? null,
  };
  const changes: DriftChange[] = [];
  for (const c of doc.changes) {
    if (!isObj(c)) return null;
    if (typeof c.key !== "string" || !c.key || typeof c.title !== "string" || typeof c.body_markdown !== "string") return null;
    if (!(DRIFT_KINDS as readonly unknown[]).includes(c.kind)) return null;
    if (!Array.isArray(c.evidence_urls) || !c.evidence_urls.every((u) => typeof u === "string")) return null;
    changes.push({ key: c.key, kind: c.kind as DriftKind, title: c.title, body_markdown: c.body_markdown, evidence_urls: [...(c.evidence_urls as string[])] });
  }
  return { template, changes };
}

export async function readTemplateDrift(
  cwd: string,
  f: DriftFetch | undefined,
  opts: { timeoutMs: number; userAgent: string; url?: string },
): Promise<DriftReport> {
  const url = opts.url ?? DRIFT_URL;
  const create = await readJson(join(cwd, "sato.create.json"));
  if ("missing" in create) return { state: "not_applicable", reason: "no sato.create.json in this directory; drift applies to repos made by create-sato-agent" };
  if ("error" in create) return { state: "unavailable", url: null, reason: `sato.create.json: ${create.error}` };
  const lock = await readJson(join(cwd, "sato.lock.json"));
  if ("missing" in lock) return { state: "unavailable", url: null, reason: "sato.create.json is present but sato.lock.json is missing" };
  if ("error" in lock) return { state: "unavailable", url: null, reason: `sato.lock.json: ${lock.error}` };
  if (!f) return { state: "unavailable", url, reason: "no fetch available in this runtime" };
  let res: Awaited<ReturnType<DriftFetch>>;
  // A ref'd timer (AbortSignal.timeout's is unref'd): the process must wait for
  // the cut-off and report it, not exit silently while the request hangs.
  const ac = new AbortController();
  const timer = setTimeout(() => ac.abort(new DOMException("drift check timed out", "TimeoutError")), opts.timeoutMs);
  try {
    res = await f(url, {
      method: "POST",
      signal: ac.signal,
      headers: { "content-type": "application/json", accept: "application/json", "user-agent": opts.userAgent },
      body: JSON.stringify({ create: create.value, lock: lock.value }),
    });
  } catch (e) {
    const err = e as Error;
    const reason = err.name === "TimeoutError" || err.name === "AbortError"
      ? `the drift check did not answer within ${opts.timeoutMs / 1000} s at ${url}`
      : `the drift check could not be read at ${url}: ${err.message}`;
    return { state: "unavailable", url, reason };
  } finally {
    clearTimeout(timer);
  }
  if (!res.ok) return { state: "unavailable", url, reason: `the drift check answered HTTP ${res.status} at ${url}` };
  let doc: unknown;
  try {
    doc = await res.json();
  } catch {
    return { state: "unavailable", url, reason: `the drift check did not return JSON at ${url}` };
  }
  const parsed = parseDriftResponse(doc);
  if (!parsed) return { state: "unavailable", url, reason: `the drift check did not return a ${DRIFT_SCHEMA} document at ${url}` };
  return { state: "checked", url, ...parsed };
}

/** Human lines for doctor. Quotes what the endpoint returned; adds nothing. */
export function driftLines(d: DriftReport): string[] {
  if (d.state === "not_applicable") return [`Template drift: not checked — ${d.reason}`];
  if (d.state === "unavailable") return [`Template drift: unavailable — ${d.reason}`];
  const t = d.template;
  const head = `Template drift: ${t.id}/${t.framework} pinned ${t.pinned_version ?? "unknown"}, latest ${t.latest_version ?? "unknown"}`
    + (t.latest_last_green ? ` (last passed its checks ${t.latest_last_green})` : "")
    + ` — ${d.changes.length === 0 ? "no changes" : `${d.changes.length} change${d.changes.length === 1 ? "" : "s"}`}`;
  const lines = [head];
  for (const c of d.changes) {
    lines.push(`  [${c.kind}] ${c.title}`);
    for (const u of c.evidence_urls) lines.push(`    evidence: ${u}`);
  }
  return lines;
}
